# Generated by Django 3.1.7 on 2021-05-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
