# Generated by Django 3.1.7 on 2021-05-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantor', '0004_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='amount',
        ),
    ]
